### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by Enigmatisms** [Dinngger/Impa#1]
Hi! I am really interested in what this repo is, and you even import `pygame` in your main script?

**Comment by Dinngger** [comment]
Now you can play the game, by yourself or AI. This game is very difficult and requires some logical reasoning to reduce search space. In my opinion, it is necessary to build higher-level module abstractions on the basis of blocks, and accurate abstract thinking is required to solve challenges, which is unimaginable for existing reinforcement learning agents.
